//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainForm
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}
