//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostelManagementSystemEntities1 : DbContext
    {
        public HostelManagementSystemEntities1()
            : base("name=HostelManagementSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentForm> StudentForms { get; set; }
        public virtual DbSet<Signin> Signin { get; set; }
        public virtual DbSet<SignUp> SignUp { get; set; }
    }
}
